services:
  vajrabox:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - $HOME/.ssh/:/root/.ssh/
      - $HOME/.gitconfig:/root/.gitconfig
      - .:/app/:cached
      - ./.vscode-server:/root/.vscode-server
    working_dir: /app/vajrabox  # Explicit working directory
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: vajrabox_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: yourpassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: